
# The lambda_venv_path module is generated by `lambda.dockerfile`.
import lambda_venv_path  # noqa


def install_secrets():
    """Add the secrets from the secret named by ENV_SECRET_ID to os.environ"""
    import boto3
    import json
    import os

    secret_id = os.environ.get('ENV_SECRET_ID')
    if not secret_id:
        return

    session = boto3.session.Session()
    client = session.client('secretsmanager')
    response = client.get_secret_value(SecretId=secret_id)
    overlay = json.loads(response['SecretString'])
    os.environ.update(overlay)


def get_lambda_handler():
    from apig_wsgi import make_lambda_handler
    from mysite.wsgi import application
    return make_lambda_handler(application)


install_secrets()
lambda_handler = get_lambda_handler()
